## SPDX-License-Identifier: BSD-3-Clause
## Copyright (C) 2019 Mike Miller
##
## .gitlab-ci.yml - GitLab CI configuration for octave-pythonic

image: mtmiller/octave

stages:
- test

before_script:
- apt-get update && apt-get install -y python-dev python-pip python3-dev python3-pip
- pip2 install numpy
- pip3 install numpy
- git clone https://github.com/catch22/octave-doctest.git /tmp/doctest
- (cd /tmp/doctest && git checkout 90af12d737d1880747b6d8f0b04a6136cc208af7) # Version 0.7.0

.test:
  stage: test
  script:
  - autoreconf -i
  - mkdir -p python${PYTHON_VERSION}
  - (cd python${PYTHON_VERSION} && ../configure PYTHON_VERSION=$PYTHON_VERSION)
  - make -C python${PYTHON_VERSION}
  - make -C python${PYTHON_VERSION} check
  - octave --path ${CI_PROJECT_DIR} --path ${CI_PROJECT_DIR}/python${PYTHON_VERSION} --path /tmp/doctest/inst --eval "exit (! doctest ('.'))"
  artifacts:
    paths:
    - python${PYTHON_VERSION}/*.log
    expire_in: 4 weeks

test python2:
  variables:
    PYTHON_VERSION: 2
  extends: .test

test python3:
  variables:
    PYTHON_VERSION: 3
  extends: .test
