## SPDX-License-Identifier: BSD-3-Clause
## Copyright (C) 2019 Mike Miller
##
## .gitlab-ci.yml - GitLab CI configuration for octave-pythonic

image: mtmiller/octave

stages:
- build
- test

before_script:
- apt-get update && apt-get install -y git python-dev python3-dev
- git clone https://github.com/catch22/octave-doctest.git /tmp/doctest
- (cd /tmp/doctest && git checkout v0.7.0)

build:
  stage: build
  script:
  - mkdir -p pkg
  - make O=pkg dist dist-zip
  artifacts:
    paths:
    - pkg/*.tar.gz
    - pkg/*.zip

.test:
  stage: test
  script:
  - mkdir -p python${PYTHON_VERSION}
  - make O=python${PYTHON_VERSION} V=1 all
  - make O=python${PYTHON_VERSION} V=1 check
  - make O=python${PYTHON_VERSION} V=1 doctest OCTAVE_PATH=/tmp/doctest/inst
  artifacts:
    paths:
    - python${PYTHON_VERSION}/*.log
    expire_in: 4 weeks

.pkg:
  stage: test
  script:
  - octave --eval "pkg install -verbose pkg/octave-pythonic-*.tar.gz"
  - octave --eval "d = pkg ('describe', 'pythonic'); assert (d{:}.name, 'pythonic')"
  - octave --eval "pkg load pythonic; v = pyversion (); assert (v(1), '${PYTHON_VERSION}')"

coverage:
  stage: test
  script:
  - pip3 install -U gcovr
  - mkdir -p coverage
  - make O=coverage V=1 CXXFLAGS="-g -O0 --coverage" all
  - make O=coverage V=1 CXXFLAGS="-g -O0 --coverage" check
  - gcovr --print-summary coverage
  coverage: '/^lines: \d+\.\d+/'

test python2:
  variables:
    PYTHON_VERSION: 2
  extends: .test

test python3:
  variables:
    PYTHON_VERSION: 3
  extends: .test

test pkg with python2:
  variables:
    PYTHON_VERSION: 2
  extends: .pkg

test pkg with python3:
  variables:
    PYTHON_VERSION: 3
  extends: .pkg
