## SPDX-License-Identifier: BSD-3-Clause
## Copyright (C) 2019 Mike Miller
##
## .gitlab-ci.yml - GitLab CI configuration for octave-pythonic

image: mtmiller/octave

stages:
- test

before_script:
- apt-get update && apt-get install -y python-dev python-pip python3-dev python3-pip
- pip2 install numpy
- pip3 install numpy
- git clone https://github.com/catch22/octave-doctest.git /tmp/doctest
- (cd /tmp/doctest && git checkout v0.7.0)

.test:
  stage: test
  script:
  - mkdir -p python${PYTHON_VERSION}
  - make O=python${PYTHON_VERSION} V=1 all
  - make O=python${PYTHON_VERSION} V=1 check
  - octave --path ${CI_PROJECT_DIR}/inst --path ${CI_PROJECT_DIR}/python${PYTHON_VERSION} --path /tmp/doctest/inst --eval "exit (! doctest ('.'))"
  artifacts:
    paths:
    - python${PYTHON_VERSION}/*.log
    expire_in: 4 weeks

.pkg:
  stage: test
  script:
  - apt-get update && apt-get install -y git
  - git archive --format=tgz --prefix=pythonic/ HEAD > pythonic.tgz
  - octave --eval "pkg install -verbose pythonic.tgz"
  - octave --eval "d = pkg ('describe', 'pythonic'); assert (d{:}.name, 'pythonic')"
  - octave --eval "pkg load pythonic; v = pyversion (); assert (v(1), '${PYTHON_VERSION}')"

test python2:
  variables:
    PYTHON_VERSION: 2
  extends: .test

test python3:
  variables:
    PYTHON_VERSION: 3
  extends: .test

test pkg with python2:
  variables:
    PYTHON_VERSION: 2
  extends: .pkg

test pkg with python3:
  variables:
    PYTHON_VERSION: 3
  extends: .pkg
